# Generated by Django 5.2.17 on 2026-09-25 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название справочника')),
                ('act', models.CharField(help_text='Например: ПП РК от 23.01.2024 № 23', max_length=200, verbose_name='Нормативный акт')),
                ('adopted', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('source_url', models.URLField(blank=True, verbose_name='Ссылка на официальный текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Справочник НДТ',
                'verbose_name_plural': 'Справочники НДТ',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmissionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('air', 'Атмосферный воздух'), ('water', 'Сбросы в воду')], default='air', max_length=6, verbose_name='Среда')),
                ('pollutant', models.CharField(max_length=80, verbose_name='Загрязняющее вещество')),
                ('fuel', models.CharField(blank=True, max_length=120, verbose_name='Топливо / сырьё')),
                ('installation', models.CharField(blank=True, max_length=200, verbose_name='Тип установки')),
                ('capacity_min', models.FloatField(blank=True, null=True, verbose_name='Мощность от, МВт')),
                ('capacity_max', models.FloatField(blank=True, null=True, verbose_name='Мощность до, МВт')),
                ('is_new_plant', models.BooleanField(blank=True, null=True, verbose_name='Для новых установок')),
                ('value_min', models.FloatField(blank=True, null=True, verbose_name='Значение от')),
                ('value_max', models.FloatField(blank=True, null=True, verbose_name='Значение до')),
                ('unit', models.CharField(default='мг/нм³', max_length=30, verbose_name='Единица')),
                ('averaging', models.CharField(blank=True, max_length=60, verbose_name='Период усреднения')),
                ('o2_reference', models.CharField(blank=True, max_length=20, verbose_name='Приведение к O₂')),
                ('section', models.CharField(help_text='Обязательно: где в официальном тексте находится значение', max_length=60, verbose_name='Таблица / пункт справочника')),
                ('verified', models.BooleanField(default=False, verbose_name='Сверено с официальным текстом')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='ndt.reference', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Технологический показатель',
                'verbose_name_plural': 'Технологические показатели',
                'ordering': ['reference', 'pollutant', 'fuel', 'capacity_min'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Номер НДТ')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование техники')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('pollutants', models.CharField(blank=True, max_length=200, verbose_name='Вещества, на которые влияет')),
                ('section', models.CharField(blank=True, max_length=60, verbose_name='Пункт справочника')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='ndt.reference', verbose_name='Справочник')),
            ],
            options={
                'verbose_name': 'Техника НДТ',
                'verbose_name_plural': 'Техники НДТ',
                'ordering': ['reference', 'code'],
            },
        ),
    ]
