# Generated by Django 5.2.17 on 2026-09-25 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('parameters', models.CharField(max_length=300, verbose_name='Измеряемые параметры')),
                ('theme', models.CharField(choices=[('climate', 'Климат (ЦУР 7, 13)'), ('water', 'Вода (ЦУР 6, 14)'), ('industry', 'Производство (ЦУР 9, 12)'), ('health', 'Здоровье и города (ЦУР 3, 11)'), ('partner', 'Отчётность (ЦУР 8, 17)')], max_length=12, verbose_name='Тема ЦУР')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Направление оборудования',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название группы')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Группа сервисов',
                'verbose_name_plural': 'Группы сервисов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('contact', models.CharField(max_length=200, verbose_name='Телефон или email')),
                ('task', models.TextField(blank=True, verbose_name='Объект и задача')),
                ('state', models.CharField(choices=[('new', 'Новая'), ('work', 'В работе'), ('done', 'Закрыта')], default='new', max_length=6, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заявка на оборудование',
                'verbose_name_plural': 'Заявки на оборудование',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('status', models.CharField(choices=[('beta', 'Бета'), ('dev', 'В разработке'), ('plan', 'Планируется')], default='plan', max_length=8, verbose_name='Статус')),
                ('theme', models.CharField(choices=[('climate', 'Климат (ЦУР 7, 13)'), ('water', 'Вода (ЦУР 6, 14)'), ('industry', 'Производство (ЦУР 9, 12)'), ('health', 'Здоровье и города (ЦУР 3, 11)'), ('partner', 'Отчётность (ЦУР 8, 17)')], max_length=12, verbose_name='Тема ЦУР')),
                ('tasks', models.CharField(blank=True, help_text='Например: ker,tech. Допустимые ключи: ker, esg, monitor, tech, waste, emis, report', max_length=200, verbose_name='Задачи (ключи через запятую)')),
                ('featured', models.BooleanField(default=False, verbose_name='Показывать крупно на главной')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicegroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
                'ordering': ['group__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Подписка на запуск',
                'verbose_name_plural': 'Подписки на запуск',
                'unique_together': {('service', 'email')},
            },
        ),
    ]
