# Generated by Django 5.2.17 on 2026-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Описание (en)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Описание (kk)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название (en)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_kk',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название (kk)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parameters_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Измеряемые параметры (en)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='parameters_kk',
            field=models.CharField(blank=True, max_length=300, verbose_name='Измеряемые параметры (kk)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Краткое описание (en)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.TextField(blank=True, verbose_name='Краткое описание (kk)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Название (en)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kk',
            field=models.CharField(blank=True, max_length=160, verbose_name='Название (kk)'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название группы (en)'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='name_kk',
            field=models.CharField(blank=True, max_length=120, verbose_name='Название группы (kk)'),
        ),
    ]
